# Generated by Django 6.0 on 2025-12-29 05:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_rename_userprofile_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='UserRegister',
        ),
    ]
