# Generated by Django 6.0 on 2025-12-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_rename_register_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
