# Generated by Django 6.0 on 2025-12-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_user_delete_userregister'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
