# Generated by Django 6.0 on 2025-12-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast', models.JSONField()),
                ('lunch', models.JSONField()),
                ('dinner', models.JSONField()),
                ('snacks', models.JSONField()),
                ('total_calories', models.IntegerField()),
                ('total_protein', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
                ('total_fat', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
