# Generated by Django 6.0 on 2025-12-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='snacks',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='total_calories',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='total_carbs',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='total_fat',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='total_protein',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks')], default='Breakfast', max_length=20),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
